# Generated by Django 4.2.5 on 2023-09-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
