# Generated by Django 4.2.5 on 2023-09-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_interest_name_alter_interest_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
